# 数据源相关信息
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://115.29.212.18:3306/gulimall_pms?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: gulimall-product
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alicloud:
      access-key: LTAI4G518dGevkoShoyoH5RT
      secret-key: gqBv7tw5iOvrfsXWmlkb0As9hmCb9W
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      # 逻辑删除赋值(可有可无)
      logic-delete-value: 1
      logic-not-delete-value: 0


server:
  port: 10000
logging:
  level:
    com.hangzhou.gulimall: debug