# 数据源相关信息
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://115.29.212.18:3306/gulimall_pms?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: gulimall-product
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alicloud:
      access-key: bwzuS4dcRBUFv0OLtFZ/H1MReyMsFt0rH7necARO69Af2EhKmU3PhPpqYVILM2JxhzTtUZ86ahh2tEisK6QZV6YkdyIiAidqOL/JsRqLYws6GECPtYOJR2nbwkuqLReD6gZIdKuKn3SLICPvpRVDRHFicRTHUUkYPk25afCpfN8=
      secret-key: DVaWHV0ds5gfH10cO/GFU9idFwxXs2Mcccl7CCXT3lc5j2JDEx0KxdTF7DRPz2xqgcXfeCdnNgl57BGJaAufMgT3ybhube/FfgLPsTd9Fbknzv9xh2HH81FsVR9m5tdu+zjoIH3j0TBC2OB+JO5fxImbqyDHV7rYe4Lm8V0EAi0=
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      # 逻辑删除赋值(可有可无)
      logic-delete-value: 1
      logic-not-delete-value: 0


server:
  port: 10000
logging:
  level:
    com.hangzhou.gulimall: debug
