# 数据源相关信息
spring:
  application:
      name: gulimall-gateway
  cloud:
    gateway:
      routes:
        - id: baiduRoute
          uri: https://www.baidu.com
          predicates:
            - Query=url, baidu
        # 前端项目暂时全部路由到 renren-fast
        - id: adminRoute
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

server:
  port: 88
