# 数据源相关信息
spring:
  application:
      name: gulimall-gateway
  cloud:
    gateway:
      routes:
        - id: baiduRoute
          uri: https://www.baidu.com
          predicates:
            - Query=url, baidu

        - id: gulimall-ware
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: gulimall-member
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        # 和adminRoute网关配置中的断言地址相似所以应该放在前面
        - id: productRoute
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        # 第三方服务网关配置
        - id: thirdPartyRoute
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>/?.*),/$\{segment}

        # 前端项目暂时全部路由到 renren-fast
        - id: adminRoute
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

server:
  port: 88
